lang: "es"
lang_direction: "ltr"
name: "Poncho Íconos"
title: "Sitio Demo Poncho Íconos"
description: "La librería de íconos oficiales para diseñar y desarrollar sitios web y aplicaciones móviles del Gobierno de la República Argentina."
athor: "Subsecretaría de Gobierno Abierto y País Digital"
color: "#0072b8"

source              : .
# Handling Reading
include             : [".htaccess", "node_modules", ".nojekyll"]
exclude             : ["config.ru", "Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
encoding            : "utf-8"
lsi                 : false
safe                : true
incremental         : false
highlighter         :rouge
gist:
  noscript: false