name: build-icons-cd

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1


      - name: Checkout Poncho
        uses: actions/checkout@master
        with: 
          repository: argob/poncho
          path: ./poncho

      - name: Copy/Create file
        run: |
          echo "Copying $FILE"
          cp -R ./iconos/dist/iconos-arg.css ./poncho/dist/css/

      - name: Push Project B
        run: |
          cd ./poncho
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "File Replicated from Iconos"
          git push