name: build-icons-cd

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: 🧪 Deploy en PONCHO
        run: |
          git clone https://github.com/argob/poncho.git
          echo "carpeta: "$GITHUB_ACTION_PATH" workspace: "$GITHUB_WORKSPACE
          cp ./dist/css/iconos-arg.css poncho/dist/css/
          cd poncho
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git