name: build-icons-cd

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🎩 Instalamos dependencias
        working-directory: /tmp
        run: |
          sudo apt install zlib1g-dev fontforge
          git clone https://github.com/bramstein/sfnt2woff-zopfli.git sfnt2woff-zopfli && cd sfnt2woff-zopfli && make && mv sfnt2woff-zopfli /usr/local/bin/sfnt2woff
          git clone --recursive https://github.com/google/woff2.git && cd woff2 && make clean all && sudo mv woff2_compress /usr/local/bin/ && sudo mv woff2_decompress /usr/local/bin/
      - name: 🎩 Instalamos Fontcustom 
        working-directory: ./
        run: |
          sudo gem install bundler fontcustom
          sudo bundle install
      - name: 🧹 Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: 🎩 Compilamos los íconos
        working-directory: ./
        run: bundle exec fontcustom compile -F
      - name: 🔨 Instalamos dependencias para la documentación
        working-directory: ./
        run: |
          npm update
          if [ -d "node_modules" ]; then
            mv node_modules ./docs/.
          fi
          cp favicon.ico ./docs/.
      - name: 🧪 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      - name: 🧪 Deploy build en el reporsitorio de Poncho
        working-directory: /tmp
        run: |
          git clone https://github.com/argob/poncho.git poncho
          cp /home/runner/work/iconos/iconos/dist/css/icono-arg.css /tmp/poncho/dist/css/.
          rm /tmp/poncho/dist/fonts/icono-arg_* -rf
          cp /home/runner/work/iconos/iconos/dist/fonts/* /tmp/poncho/dist/fonts/.

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/argob/poncho.git
