name: build-icons-cd

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: ./iconos
      - name: 🎩 Instalamos dependencias
        working-directory: /tmp
        run: |
          sudo apt install zlib1g-dev fontforge
          git clone https://github.com/bramstein/sfnt2woff-zopfli.git sfnt2woff-zopfli && cd sfnt2woff-zopfli && make && mv sfnt2woff-zopfli /usr/local/bin/sfnt2woff
          git clone --recursive https://github.com/google/woff2.git && cd woff2 && make clean all && sudo mv woff2_compress /usr/local/bin/ && sudo mv woff2_decompress /usr/local/bin/
      - name: 🎩 Instalamos Fontcustom 
        working-directory: ./iconos
        run: |
          sudo gem install bundler fontcustom
          sudo bundle install
      - name: 🧹 Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: 🎩 Compilamos los íconos
        working-directory: ./iconos
        run: bundle exec fontcustom compile -F
      - name: 🔨 Instalamos dependencias para la documentación
        working-directory: ./iconos
        run: |
          cp favicon.ico ./docs/.
      - name: 🧪 Deploy build
        working-directory: ./iconos
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      - name: Checkout Poncho
        uses: actions/checkout@master
        with: 
          repository: argob/poncho
          path: ./poncho

      - name: Copy/Create file
        run: |
          echo "Copying $FILE"
          cp -R ./iconos/dist/css/icono-arg.css ./poncho/dist/css/
#      - name: Push Project B
#        run: |
#          cd ./poncho
#          git add .
#          git config user.name "${GITHUB_ACTOR}"
#          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#          git commit -am "File Replicated from Iconos"
#          git push