name: build-icons-cd

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🎩 Instalamos dependencias
        working-directory: /tmp
        run: |
          sudo apt install zlib1g-dev fontforge
          git clone https://github.com/bramstein/sfnt2woff-zopfli.git sfnt2woff-zopfli && cd sfnt2woff-zopfli && make && mv sfnt2woff-zopfli /usr/local/bin/sfnt2woff
          git clone --recursive https://github.com/google/woff2.git && cd woff2 && make clean all && sudo mv woff2_compress /usr/local/bin/ && sudo mv woff2_decompress /usr/local/bin/
      - name: 🎩 Instalamos Fontcustom 
        working-directory: ./
        run: |
          sudo gem install bundler fontcustom
          sudo bundle install
      - name: 🧹 Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: 🎩 Compilamos los íconos
        working-directory: ./
        run: bundle exec fontcustom compile -F
      - name: 🔨 Instalamos dependencias para la documentación
        working-directory: ./
        run: |
          npm update
          if [ -d "node_modules" ]; then
            mv node_modules ./docs/.
          fi
          cp favicon.ico ./docs/.
      - name: 🧪 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      - name: Enviamos los archivos finales a Poncho
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "./dist/css/icono-arg.css"
          destination_repo: "argob/poncho"
          destination_folder: "dist/css/"
          user_email: "${GITHUB_ACTOR}@users.noreply.github.com"
          user_name: "${GITHUB_ACTOR}"
          commit_message: 'Cargamos la última versión de íconos desde el repositorio de íconos.'